enum STATUS {
  ACTIVE = 'ACTIVE',
  BLOCK = 'BLOCK',
  PENDING = 'PENDING',
  FINISH = 'FINISH',
  DELETE = 'DELETE',
  STOP = 'STOP',
  PAUSE = 'PAUSE',
}

enum TYPE_OF_WITHDRAW {
  TRANSFER = 'TRANSFER',
  WITHDRAW = 'WITHDRAW',
  TRANSFER_TO_WALLET = 'TRANSFER_TO_WALLET',
  TRANSFER_TO_COPYTRADE = 'TRANSFER_TO_COPYTRADE',
}

enum RATE {
  FEE_TO_EXPERT = 5 / 100,
  FEE_TO_TRADING = 5 / 100,
}

enum TYPE_OF_CLIENT {
  ADMIN = 'ADMIN',
  USER = 'USER',
  EXPERT = 'EXPERT',
}

enum TYPE_OF_WALLET {
  WALLET = 'WALLET',
  COPY_TRADE = 'COPY_TRADE',
}

export default {
  STATUS,
  RATE,
  TYPE_OF_WITHDRAW,
  TYPE_OF_CLIENT,
  TYPE_OF_WALLET,
};
